import { Language } from '../types';

export const LANGUAGES: Language[] = [
  // Common / Indian Languages requested
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    script: 'Latin',
    family: 'Indo-European (Germanic)',
    region: 'North America & Global',
    flag: '🇬🇧',
    lat: 51.5074,
    lng: -0.1278,
    popular: true,
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    script: 'Tamil Brahmi-derived',
    family: 'Dravidian',
    region: 'Tamil Nadu, Sri Lanka & SE Asia',
    flag: '🇮🇳',
    lat: 13.0827,
    lng: 80.2707,
    popular: true,
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    script: 'Devanagari',
    family: 'Indo-European (Indo-Aryan)',
    region: 'Northern & Central India',
    flag: '🇮🇳',
    lat: 28.6139,
    lng: 77.209,
    popular: true,
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    script: 'Telugu Script',
    family: 'Dravidian',
    region: 'Andhra Pradesh & Telangana',
    flag: '🇮🇳',
    lat: 17.385,
    lng: 78.4867,
    popular: true,
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    script: 'Malayalam Script',
    family: 'Dravidian',
    region: 'Kerala, India',
    flag: '🇮🇳',
    lat: 8.5241,
    lng: 76.9366,
    popular: true,
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    script: 'Kannada Script',
    family: 'Dravidian',
    region: 'Karnataka, India',
    flag: '🇮🇳',
    lat: 12.9716,
    lng: 77.5946,
    popular: true,
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    script: 'Bengali-Assamese',
    family: 'Indo-European (Indo-Aryan)',
    region: 'Bengal & Bangladesh',
    flag: '🇧🇩',
    lat: 23.8103,
    lng: 90.4125,
    popular: true,
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    script: 'Devanagari (Balbodh)',
    family: 'Indo-European (Indo-Aryan)',
    region: 'Maharashtra, India',
    flag: '🇮🇳',
    lat: 19.076,
    lng: 72.8777,
    popular: true,
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    script: 'Gujarati Script',
    family: 'Indo-European (Indo-Aryan)',
    region: 'Gujarat, India',
    flag: '🇮🇳',
    lat: 23.0225,
    lng: 72.5714,
  },
  {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    script: 'Gurmukhi',
    family: 'Indo-European (Indo-Aryan)',
    region: 'Punjab (India & Pakistan)',
    flag: '🇮🇳',
    lat: 31.634,
    lng: 74.8723,
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    script: 'Perso-Arabic (Nastaliq)',
    family: 'Indo-European (Indo-Aryan)',
    region: 'South Asia',
    flag: '🇵🇰',
    rtl: true,
    lat: 33.6844,
    lng: 73.0479,
  },

  // Major Global Languages
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    script: 'Latin',
    family: 'Indo-European (Romance)',
    region: 'Spain & Latin America',
    flag: '🇪🇸',
    lat: 40.4168,
    lng: -3.7038,
    popular: true,
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    script: 'Latin',
    family: 'Indo-European (Romance)',
    region: 'France, Canada & Francophonie',
    flag: '🇫🇷',
    lat: 48.8566,
    lng: 2.3522,
    popular: true,
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    script: 'Latin',
    family: 'Indo-European (Germanic)',
    region: 'Central Europe (DACH)',
    flag: '🇩🇪',
    lat: 52.52,
    lng: 13.405,
    popular: true,
  },
  {
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    script: 'Latin',
    family: 'Indo-European (Romance)',
    region: 'Italy & Southern Europe',
    flag: '🇮🇹',
    lat: 41.9028,
    lng: 12.4964,
    popular: true,
  },
  {
    code: 'pt',
    name: 'Portuguese',
    nativeName: 'Português',
    script: 'Latin',
    family: 'Indo-European (Romance)',
    region: 'Brazil & Portugal',
    flag: '🇵🇹',
    lat: -15.7975,
    lng: -47.8919,
    popular: true,
  },
  {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    script: 'Arabic Script',
    family: 'Afroasiatic (Semitic)',
    region: 'Middle East & North Africa',
    flag: '🇸🇦',
    rtl: true,
    lat: 24.7136,
    lng: 46.6753,
    popular: true,
  },
  {
    code: 'zh',
    name: 'Chinese (Simplified)',
    nativeName: '中文 (简体)',
    script: 'Simplified Hanzi',
    family: 'Sino-Tibetan',
    region: 'China, Singapore',
    flag: '🇨🇳',
    lat: 39.9042,
    lng: 116.4074,
    popular: true,
  },
  {
    code: 'zh-TW',
    name: 'Chinese (Traditional)',
    nativeName: '中文 (繁體)',
    script: 'Traditional Hanzi',
    family: 'Sino-Tibetan',
    region: 'Taiwan, Hong Kong',
    flag: '🇹🇼',
    lat: 25.033,
    lng: 121.5654,
  },
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    script: 'Kanji & Kana (Hiragana/Katakana)',
    family: 'Japonic',
    region: 'Japan',
    flag: '🇯🇵',
    lat: 35.6762,
    lng: 139.6503,
    popular: true,
  },
  {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    script: 'Hangul',
    family: 'Koreanic',
    region: 'South Korea & East Asia',
    flag: '🇰🇷',
    lat: 37.5665,
    lng: 126.978,
    popular: true,
  },
  {
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    script: 'Cyrillic',
    family: 'Indo-European (Slavic)',
    region: 'Eastern Europe & North Asia',
    flag: '🇷🇺',
    lat: 55.7558,
    lng: 37.6173,
    popular: true,
  },
  {
    code: 'nl',
    name: 'Dutch',
    nativeName: 'Nederlands',
    script: 'Latin',
    family: 'Indo-European (Germanic)',
    region: 'Netherlands & Flanders',
    flag: '🇳🇱',
    lat: 52.3676,
    lng: 4.9041,
  },
  {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    script: 'Latin (Turkish alphabet)',
    family: 'Turkic',
    region: 'Turkey & Anatolia',
    flag: '🇹🇷',
    lat: 41.0082,
    lng: 28.9784,
    popular: true,
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    script: 'Latin (Chữ Quốc ngữ)',
    family: 'Austroasiatic',
    region: 'Vietnam & SE Asia',
    flag: '🇻🇳',
    lat: 21.0285,
    lng: 105.8542,
  },
  {
    code: 'th',
    name: 'Thai',
    nativeName: 'ไทย',
    script: 'Thai Script',
    family: 'Kra-Dai',
    region: 'Thailand & SE Asia',
    flag: '🇹🇭',
    lat: 13.7563,
    lng: 100.5018,
  },
  {
    code: 'id',
    name: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    script: 'Latin',
    family: 'Austronesian (Malayo-Polynesian)',
    region: 'Indonesia & Maritime SE Asia',
    flag: '🇮🇩',
    lat: -6.2088,
    lng: 106.8456,
  },
  {
    code: 'pl',
    name: 'Polish',
    nativeName: 'Polski',
    script: 'Latin',
    family: 'Indo-European (Slavic)',
    region: 'Poland & Central Europe',
    flag: '🇵🇱',
    lat: 52.2297,
    lng: 21.0122,
  },
  {
    code: 'sv',
    name: 'Swedish',
    nativeName: 'Svenska',
    script: 'Latin',
    family: 'Indo-European (Germanic)',
    region: 'Sweden & Scandinavia',
    flag: '🇸🇪',
    lat: 59.3293,
    lng: 18.0686,
  },
  {
    code: 'uk',
    name: 'Ukrainian',
    nativeName: 'Українська',
    script: 'Cyrillic',
    family: 'Indo-European (Slavic)',
    region: 'Ukraine & Eastern Europe',
    flag: '🇺🇦',
    lat: 50.4501,
    lng: 30.5234,
  },
  {
    code: 'el',
    name: 'Greek',
    nativeName: 'Ελληνικά',
    script: 'Greek Alphabet',
    family: 'Indo-European (Hellenic)',
    region: 'Greece & Eastern Mediterranean',
    flag: '🇬🇷',
    lat: 37.9838,
    lng: 23.7275,
  },
  {
    code: 'he',
    name: 'Hebrew',
    nativeName: 'עברית',
    script: 'Hebrew Alphabet',
    family: 'Afroasiatic (Semitic)',
    region: 'Israel & Levant',
    flag: '🇮🇱',
    rtl: true,
    lat: 31.7683,
    lng: 35.2137,
  },
];

export const AUTO_DETECT_OPTION: Language = {
  code: 'auto',
  name: 'Auto Detect',
  nativeName: 'Detect Language',
  script: 'Multi-Script Neural Scanner',
  family: 'Automatic Spectral Detection',
  region: 'Worldwide',
  flag: '✨',
  lat: 0,
  lng: 0,
};

export function getLanguageByCode(code: string): Language {
  if (code === 'auto') return AUTO_DETECT_OPTION;
  const lang = LANGUAGES.find((l) => l.code.toLowerCase() === code.toLowerCase());
  if (lang) return lang;
  return {
    code,
    name: code.toUpperCase(),
    nativeName: code.toUpperCase(),
    script: 'Standard Script',
    family: 'Natural Language',
    region: 'Global',
    flag: '🌐',
    lat: 0,
    lng: 0,
  };
}
